name: ChildPipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out pipeline repository
      - name: 'Log payload'
        run: |
          echo ${{ github.event.client_payload.ApplicationDetails.AppName }}
          echo ${{ github.event.client_payload.ApplicationDetails.AppCMDBID }}
          echo ${{ github.event.client_payload.RequestorName }}
          echo ${{ github.event.client_payload.ApplicationDetails.ProjectName }}
          echo ${{ github.event.client_payload.Service_req_number }}
          echo ${{ github.event.client_payload.Message }}
          echo ${{ github.event.client_payload.DependencyDetails.PackageRegistry }}
          echo ${{ github.event.client_payload.DependencyDetails.PackageName }}
          echo ${{ github.event.client_payload.DependencyDetails.DockerImageName }}
          echo ${{ github.event.client_payload.DependencyDetails.GroupId }}
          echo ${{ github.event.client_payload.DependencyDetails.ArtifactId }}
          echo ${{ github.event.client_payload.DependencyDetails.VersionNumber }}
          echo ${{ github.event.client_payload.Platform }}